"""
Auto-generated by RetroLang compiler.
Game     : 'NeonTetris'
Mode     : tetris
Source   : embedded literals — no RetroLang runtime needed.
"""

import sys
import random
import pygame

# ---- compiled-in configuration ----
GAME_NAME    = 'NeonTetris'
GRID_W       = 10
GRID_H       = 20
BLOCK_SIZE   = 32
BG_COLOR     = (13, 13, 26)
TEXT_COLOR   = (255, 255, 255)
GRID_COLOR   = (26, 26, 46)
ACCENT_COLOR = (255, 0, 255)
HUD_HEIGHT   = 64
WINDOW_W     = GRID_W * BLOCK_SIZE
WINDOW_H     = GRID_H * BLOCK_SIZE + HUD_HEIGHT

PIECES = [
    {'name': 'I', 'shape': [[1, 1, 1, 1]], 'color': (0, 255, 255)},
    {'name': 'O', 'shape': [[1, 1], [1, 1]], 'color': (255, 215, 0)},
    {'name': 'T', 'shape': [[0, 1, 0], [1, 1, 1]], 'color': (255, 0, 255)},
    {'name': 'S', 'shape': [[0, 1, 1], [1, 1, 0]], 'color': (0, 255, 136)},
    {'name': 'Z', 'shape': [[1, 1, 0], [0, 1, 1]], 'color': (255, 68, 68)},
    {'name': 'L', 'shape': [[1, 0], [1, 0], [1, 1]], 'color': (255, 136, 0)},
    {'name': 'J', 'shape': [[0, 1], [0, 1], [1, 1]], 'color': (136, 0, 255)},
]

GRAVITY_MS      = 500
SPEEDUP_LINES   = 5
SCORE_PER_LINE  = 100
BONUS_TETRIS    = 400
GAME_OVER_CONDS = ['on_top_collision']

KEYMAP = {
        'move_left': pygame.K_LEFT,
        'move_right': pygame.K_RIGHT,
        'rotate': pygame.K_UP,
        'soft_drop': pygame.K_DOWN,
        'hard_drop': pygame.K_SPACE,
        'pause': pygame.K_p,
        'restart': pygame.K_r,
        'quit': pygame.K_q
}


def new_piece():
    proto = random.choice(PIECES)
    shape = [row[:] for row in proto["shape"]]
    return {
        "name": proto["name"],
        "shape": shape,
        "color": proto["color"],
        "x": GRID_W // 2 - len(shape[0]) // 2,
        "y": 0,
    }


def rotate_shape(shape):
    return [list(row) for row in zip(*shape[::-1])]


def collides(board, piece, dx=0, dy=0, shape=None):
    shape = shape if shape is not None else piece["shape"]
    for r, row in enumerate(shape):
        for c, cell in enumerate(row):
            if not cell:
                continue
            x = piece["x"] + c + dx
            y = piece["y"] + r + dy
            if x < 0 or x >= GRID_W or y >= GRID_H:
                return True
            if y >= 0 and board[y][x] is not None:
                return True
    return False


def lock(board, piece):
    for r, row in enumerate(piece["shape"]):
        for c, cell in enumerate(row):
            if cell:
                y = piece["y"] + r
                x = piece["x"] + c
                if 0 <= y < GRID_H and 0 <= x < GRID_W:
                    board[y][x] = piece["color"]


def clear_lines(board):
    new_board = [row for row in board if any(cell is None for cell in row)]
    cleared = GRID_H - len(new_board)
    while len(new_board) < GRID_H:
        new_board.insert(0, [None] * GRID_W)
    return new_board, cleared


def draw_block(surface, x, y, color):
    rect = pygame.Rect(x * BLOCK_SIZE, y * BLOCK_SIZE + HUD_HEIGHT,
                       BLOCK_SIZE, BLOCK_SIZE)
    pygame.draw.rect(surface, color, rect)
    pygame.draw.rect(surface, GRID_COLOR, rect, 1)


def draw_hud(surface, font, score, lines, level, game_over):
    pygame.draw.rect(surface, (0, 0, 0), (0, 0, WINDOW_W, HUD_HEIGHT))
    txt = f"SCORE {score}   LINES {lines}   LEVEL {level}"
    surface.blit(font.render(txt, True, TEXT_COLOR), (10, 8))
    surface.blit(font.render(GAME_NAME, True, ACCENT_COLOR), (10, 32))
    if game_over:
        msg = font.render("GAME OVER — press R to restart, Q to quit", True, ACCENT_COLOR)
        surface.blit(msg, (WINDOW_W // 2 - msg.get_width() // 2,
                           WINDOW_H // 2 - msg.get_height() // 2))


def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption(GAME_NAME + " — RetroLang")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("Courier", 18, bold=True)

    def reset():
        return {
            "board": [[None] * GRID_W for _ in range(GRID_H)],
            "piece": new_piece(),
            "score": 0,
            "lines": 0,
            "level": 1,
            "drop_timer": 0,
            "drop_interval": GRAVITY_MS,
            "paused": False,
            "game_over": False,
        }

    state = reset()

    while True:
        dt = clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN:
                if event.key == KEYMAP.get("quit"):
                    pygame.quit(); sys.exit(0)
                if event.key == KEYMAP.get("restart"):
                    state = reset(); continue
                if state["game_over"]:
                    if event.key == pygame.K_r:
                        state = reset()
                    elif event.key == pygame.K_q:
                        pygame.quit(); sys.exit(0)
                    continue
                if event.key == KEYMAP.get("pause"):
                    state["paused"] = not state["paused"]
                if state["paused"]:
                    continue
                p = state["piece"]
                if event.key == KEYMAP.get("move_left") and not collides(state["board"], p, dx=-1):
                    p["x"] -= 1
                elif event.key == KEYMAP.get("move_right") and not collides(state["board"], p, dx=1):
                    p["x"] += 1
                elif event.key == KEYMAP.get("soft_drop") and not collides(state["board"], p, dy=1):
                    p["y"] += 1
                elif event.key == KEYMAP.get("rotate"):
                    rotated = rotate_shape(p["shape"])
                    if not collides(state["board"], p, shape=rotated):
                        p["shape"] = rotated
                elif event.key == KEYMAP.get("hard_drop"):
                    while not collides(state["board"], p, dy=1):
                        p["y"] += 1

        if not state["paused"] and not state["game_over"]:
            state["drop_timer"] += dt
            if state["drop_timer"] >= state["drop_interval"]:
                state["drop_timer"] = 0
                p = state["piece"]
                if collides(state["board"], p, dy=1):
                    lock(state["board"], p)
                    state["board"], cleared = clear_lines(state["board"])
                    if cleared:
                        gained = SCORE_PER_LINE * cleared
                        if cleared == 4:
                            gained += BONUS_TETRIS
                        state["score"] += gained
                        state["lines"] += cleared
                        new_level = 1 + state["lines"] // SPEEDUP_LINES
                        if new_level > state["level"]:
                            state["level"] = new_level
                            state["drop_interval"] = max(60, int(GRAVITY_MS * (0.85 ** (new_level - 1))))
                    state["piece"] = new_piece()
                    if "on_top_collision" in GAME_OVER_CONDS and collides(state["board"], state["piece"]):
                        state["game_over"] = True
                else:
                    p["y"] += 1

        screen.fill(BG_COLOR)
        for y in range(GRID_H):
            for x in range(GRID_W):
                cell = state["board"][y][x]
                if cell is not None:
                    draw_block(screen, x, y, cell)
        if not state["game_over"]:
            p = state["piece"]
            for r, row in enumerate(p["shape"]):
                for c, cell in enumerate(row):
                    if cell:
                        draw_block(screen, p["x"] + c, p["y"] + r, p["color"])
        draw_hud(screen, font, state["score"], state["lines"], state["level"], state["game_over"])
        pygame.display.flip()


if __name__ == "__main__":
    main()
