"""
Auto-generated by RetroLang compiler.
Game     : 'RetroSnake'
Mode     : snake
Source   : embedded literals — no RetroLang runtime needed.
"""

import sys
import random
import pygame

# ---- compiled-in configuration ----
GAME_NAME    = 'RetroSnake'
GRID_W       = 20
GRID_H       = 20
BLOCK_SIZE   = 24
BG_COLOR     = (0, 17, 0)
TEXT_COLOR   = (51, 255, 51)
GRID_COLOR   = (0, 51, 0)
ACCENT_COLOR = (51, 255, 51)
HUD_HEIGHT   = 64
WINDOW_W     = GRID_W * BLOCK_SIZE
WINDOW_H     = GRID_H * BLOCK_SIZE + HUD_HEIGHT

START_LENGTH    = 3
FOOD_COUNT      = 1
WRAP_EDGES      = False
SPEED_MS        = 200
SCORE_PER_FOOD  = 50
GAME_OVER_CONDS = ['on_self_collision', 'on_wall_collision']

SNAKE_COLOR     = ACCENT_COLOR
FOOD_COLOR      = TEXT_COLOR

KEYMAP = {
        'move_up': pygame.K_UP,
        'move_down': pygame.K_DOWN,
        'move_left': pygame.K_LEFT,
        'move_right': pygame.K_RIGHT,
        'pause': pygame.K_p,
        'restart': pygame.K_r,
        'quit': pygame.K_q
}

DIRS = {
    "move_up":    (0, -1),
    "move_down":  (0,  1),
    "move_left":  (-1, 0),
    "move_right": (1,  0),
}


def spawn_food(snake, foods):
    while True:
        x = random.randrange(GRID_W)
        y = random.randrange(GRID_H)
        if (x, y) not in snake and (x, y) not in foods:
            return (x, y)


def draw_block(surface, x, y, color):
    rect = pygame.Rect(x * BLOCK_SIZE, y * BLOCK_SIZE + HUD_HEIGHT,
                       BLOCK_SIZE, BLOCK_SIZE)
    pygame.draw.rect(surface, color, rect)
    pygame.draw.rect(surface, GRID_COLOR, rect, 1)


def draw_hud(surface, font, score, length, game_over):
    pygame.draw.rect(surface, (0, 0, 0), (0, 0, WINDOW_W, HUD_HEIGHT))
    surface.blit(font.render(f"SCORE {score}   LENGTH {length}", True, TEXT_COLOR), (10, 8))
    surface.blit(font.render(GAME_NAME, True, ACCENT_COLOR), (10, 32))
    if game_over:
        msg = font.render("GAME OVER — press R to restart, Q to quit", True, ACCENT_COLOR)
        surface.blit(msg, (WINDOW_W // 2 - msg.get_width() // 2,
                           WINDOW_H // 2 - msg.get_height() // 2))


def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption(GAME_NAME + " — RetroLang")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("Courier", 18, bold=True)

    def reset():
        cx, cy = GRID_W // 2, GRID_H // 2
        snake = [(cx - i, cy) for i in range(START_LENGTH)]
        foods = []
        for _ in range(FOOD_COUNT):
            foods.append(spawn_food(snake, foods))
        return {
            "snake": snake,
            "dir": (1, 0),
            "next_dir": (1, 0),
            "foods": foods,
            "score": 0,
            "tick": 0,
            "paused": False,
            "game_over": False,
        }

    state = reset()

    while True:
        dt = clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN:
                if event.key == KEYMAP.get("quit"):
                    pygame.quit(); sys.exit(0)
                if event.key == KEYMAP.get("restart"):
                    state = reset(); continue
                if state["game_over"]:
                    if event.key == pygame.K_r:
                        state = reset()
                    elif event.key == pygame.K_q:
                        pygame.quit(); sys.exit(0)
                    continue
                if event.key == KEYMAP.get("pause"):
                    state["paused"] = not state["paused"]
                for action, vec in DIRS.items():
                    if event.key == KEYMAP.get(action):
                        # disallow direct reversal
                        if (vec[0] + state["dir"][0], vec[1] + state["dir"][1]) != (0, 0):
                            state["next_dir"] = vec

        if not state["paused"] and not state["game_over"]:
            state["tick"] += dt
            if state["tick"] >= SPEED_MS:
                state["tick"] = 0
                state["dir"] = state["next_dir"]
                hx, hy = state["snake"][0]
                dx, dy = state["dir"]
                nx, ny = hx + dx, hy + dy
                if WRAP_EDGES:
                    nx %= GRID_W; ny %= GRID_H
                else:
                    if (nx < 0 or nx >= GRID_W or ny < 0 or ny >= GRID_H):
                        if "on_wall_collision" in GAME_OVER_CONDS:
                            state["game_over"] = True
                if not state["game_over"]:
                    if (nx, ny) in state["snake"] and "on_self_collision" in GAME_OVER_CONDS:
                        state["game_over"] = True
                if not state["game_over"]:
                    state["snake"].insert(0, (nx, ny))
                    if (nx, ny) in state["foods"]:
                        state["foods"].remove((nx, ny))
                        state["foods"].append(spawn_food(state["snake"], state["foods"]))
                        state["score"] += SCORE_PER_FOOD
                    else:
                        state["snake"].pop()

        screen.fill(BG_COLOR)
        for (fx, fy) in state["foods"]:
            draw_block(screen, fx, fy, FOOD_COLOR)
        for (sx, sy) in state["snake"]:
            draw_block(screen, sx, sy, SNAKE_COLOR)
        draw_hud(screen, font, state["score"], len(state["snake"]), state["game_over"])
        pygame.display.flip()


if __name__ == "__main__":
    main()
