"""
RetroLang code generator (Phase 6).

Lowers the optimized GameIR into a self-contained Python/pygame module.
The generated module is plain Python (no RetroLang imports), so it can
be saved with --emit-python and run independently.

Two templates:
  * tetris  — falling-piece engine with line clearing and progressive speed
  * snake   — directional-movement engine with food and growth

The generator embeds piece shapes, colors, rules, and key bindings as
literals into the emitted code. Each emitted file ends with a top-level
`main()` invocation so executing the file launches the game window.
"""

from typing import Dict
from .ir import GameIR


PYGAME_KEY_MAP = {
    "KEY_LEFT": "pygame.K_LEFT",
    "KEY_RIGHT": "pygame.K_RIGHT",
    "KEY_UP": "pygame.K_UP",
    "KEY_DOWN": "pygame.K_DOWN",
    "KEY_SPACE": "pygame.K_SPACE",
    "KEY_RETURN": "pygame.K_RETURN",
    "KEY_ESCAPE": "pygame.K_ESCAPE",
    "KEY_P": "pygame.K_p",
    "KEY_Q": "pygame.K_q",
    "KEY_R": "pygame.K_r",
    "KEY_W": "pygame.K_w",
    "KEY_A": "pygame.K_a",
    "KEY_S": "pygame.K_s",
    "KEY_D": "pygame.K_d",
}

THEME_PALETTES = {
    # secondary palette colors used for HUD/grid lines
    "NEON":      {"text": "#FFFFFF", "grid": "#1a1a2e", "accent": "#FF00FF"},
    "CRT_GREEN": {"text": "#33FF33", "grid": "#003300", "accent": "#33FF33"},
    "AMBER":     {"text": "#FFB000", "grid": "#332200", "accent": "#FFB000"},
    "MONO":      {"text": "#DDDDDD", "grid": "#222222", "accent": "#FFFFFF"},
    "DEFAULT":   {"text": "#FFFFFF", "grid": "#222222", "accent": "#888888"},
}


def _hex_to_rgb_tuple(hex_str: str) -> str:
    h = hex_str.lstrip("#")
    return f"({int(h[0:2], 16)}, {int(h[2:4], 16)}, {int(h[4:6], 16)})"


def _controls_dict(controls: Dict[str, str]) -> str:
    parts = []
    for action, key in controls.items():
        parts.append(f"        {action!r}: {PYGAME_KEY_MAP.get(key, 'None')}")
    return ",\n".join(parts) if parts else "        # no bindings"


def generate(ir: GameIR) -> str:
    """Return a complete Python source string for the compiled game."""
    if ir.mode == "snake":
        return _gen_snake(ir)
    return _gen_tetris(ir)


# ---------- shared header ----------

def _header(ir: GameIR) -> str:
    palette = THEME_PALETTES.get(ir.theme, THEME_PALETTES["DEFAULT"])
    return f'''"""
Auto-generated by RetroLang compiler.
Game     : {ir.name!r}
Mode     : {ir.mode}
Source   : embedded literals — no RetroLang runtime needed.
"""

import sys
import random
import pygame

# ---- compiled-in configuration ----
GAME_NAME    = {ir.name!r}
GRID_W       = {ir.grid_w}
GRID_H       = {ir.grid_h}
BLOCK_SIZE   = {ir.block_size}
BG_COLOR     = {_hex_to_rgb_tuple(ir.background)}
TEXT_COLOR   = {_hex_to_rgb_tuple(palette['text'])}
GRID_COLOR   = {_hex_to_rgb_tuple(palette['grid'])}
ACCENT_COLOR = {_hex_to_rgb_tuple(palette['accent'])}
HUD_HEIGHT   = 64
WINDOW_W     = GRID_W * BLOCK_SIZE
WINDOW_H     = GRID_H * BLOCK_SIZE + HUD_HEIGHT
'''


# ---------- tetris template ----------

def _gen_tetris(ir: GameIR) -> str:
    pieces_literal = "PIECES = [\n"
    for p in ir.pieces:
        pieces_literal += (
            f"    {{'name': {p.name!r}, "
            f"'shape': {p.shape!r}, "
            f"'color': {_hex_to_rgb_tuple(p.color)}}},\n"
        )
    pieces_literal += "]"

    body = f'''
{pieces_literal}

GRAVITY_MS      = {ir.gravity_speed}
SPEEDUP_LINES   = {ir.speedup_every}
SCORE_PER_LINE  = {ir.score_per_line}
BONUS_TETRIS    = {ir.bonus_tetris}
GAME_OVER_CONDS = {ir.game_over_conditions!r}

KEYMAP = {{
{_controls_dict(ir.controls)}
}}


def new_piece():
    proto = random.choice(PIECES)
    shape = [row[:] for row in proto["shape"]]
    return {{
        "name": proto["name"],
        "shape": shape,
        "color": proto["color"],
        "x": GRID_W // 2 - len(shape[0]) // 2,
        "y": 0,
    }}


def rotate_shape(shape):
    return [list(row) for row in zip(*shape[::-1])]


def collides(board, piece, dx=0, dy=0, shape=None):
    shape = shape if shape is not None else piece["shape"]
    for r, row in enumerate(shape):
        for c, cell in enumerate(row):
            if not cell:
                continue
            x = piece["x"] + c + dx
            y = piece["y"] + r + dy
            if x < 0 or x >= GRID_W or y >= GRID_H:
                return True
            if y >= 0 and board[y][x] is not None:
                return True
    return False


def lock(board, piece):
    for r, row in enumerate(piece["shape"]):
        for c, cell in enumerate(row):
            if cell:
                y = piece["y"] + r
                x = piece["x"] + c
                if 0 <= y < GRID_H and 0 <= x < GRID_W:
                    board[y][x] = piece["color"]


def clear_lines(board):
    new_board = [row for row in board if any(cell is None for cell in row)]
    cleared = GRID_H - len(new_board)
    while len(new_board) < GRID_H:
        new_board.insert(0, [None] * GRID_W)
    return new_board, cleared


def draw_block(surface, x, y, color):
    rect = pygame.Rect(x * BLOCK_SIZE, y * BLOCK_SIZE + HUD_HEIGHT,
                       BLOCK_SIZE, BLOCK_SIZE)
    pygame.draw.rect(surface, color, rect)
    pygame.draw.rect(surface, GRID_COLOR, rect, 1)


def draw_hud(surface, font, score, lines, level, game_over):
    pygame.draw.rect(surface, (0, 0, 0), (0, 0, WINDOW_W, HUD_HEIGHT))
    txt = f"SCORE {{score}}   LINES {{lines}}   LEVEL {{level}}"
    surface.blit(font.render(txt, True, TEXT_COLOR), (10, 8))
    surface.blit(font.render(GAME_NAME, True, ACCENT_COLOR), (10, 32))
    if game_over:
        msg = font.render("GAME OVER — press R to restart, Q to quit", True, ACCENT_COLOR)
        surface.blit(msg, (WINDOW_W // 2 - msg.get_width() // 2,
                           WINDOW_H // 2 - msg.get_height() // 2))


def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption(GAME_NAME + " — RetroLang")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("Courier", 18, bold=True)

    def reset():
        return {{
            "board": [[None] * GRID_W for _ in range(GRID_H)],
            "piece": new_piece(),
            "score": 0,
            "lines": 0,
            "level": 1,
            "drop_timer": 0,
            "drop_interval": GRAVITY_MS,
            "paused": False,
            "game_over": False,
        }}

    state = reset()

    while True:
        dt = clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN:
                if event.key == KEYMAP.get("quit"):
                    pygame.quit(); sys.exit(0)
                if event.key == KEYMAP.get("restart"):
                    state = reset(); continue
                if state["game_over"]:
                    if event.key == pygame.K_r:
                        state = reset()
                    elif event.key == pygame.K_q:
                        pygame.quit(); sys.exit(0)
                    continue
                if event.key == KEYMAP.get("pause"):
                    state["paused"] = not state["paused"]
                if state["paused"]:
                    continue
                p = state["piece"]
                if event.key == KEYMAP.get("move_left") and not collides(state["board"], p, dx=-1):
                    p["x"] -= 1
                elif event.key == KEYMAP.get("move_right") and not collides(state["board"], p, dx=1):
                    p["x"] += 1
                elif event.key == KEYMAP.get("soft_drop") and not collides(state["board"], p, dy=1):
                    p["y"] += 1
                elif event.key == KEYMAP.get("rotate"):
                    rotated = rotate_shape(p["shape"])
                    if not collides(state["board"], p, shape=rotated):
                        p["shape"] = rotated
                elif event.key == KEYMAP.get("hard_drop"):
                    while not collides(state["board"], p, dy=1):
                        p["y"] += 1

        if not state["paused"] and not state["game_over"]:
            state["drop_timer"] += dt
            if state["drop_timer"] >= state["drop_interval"]:
                state["drop_timer"] = 0
                p = state["piece"]
                if collides(state["board"], p, dy=1):
                    lock(state["board"], p)
                    state["board"], cleared = clear_lines(state["board"])
                    if cleared:
                        gained = SCORE_PER_LINE * cleared
                        if cleared == 4:
                            gained += BONUS_TETRIS
                        state["score"] += gained
                        state["lines"] += cleared
                        new_level = 1 + state["lines"] // SPEEDUP_LINES
                        if new_level > state["level"]:
                            state["level"] = new_level
                            state["drop_interval"] = max(60, int(GRAVITY_MS * (0.85 ** (new_level - 1))))
                    state["piece"] = new_piece()
                    if "on_top_collision" in GAME_OVER_CONDS and collides(state["board"], state["piece"]):
                        state["game_over"] = True
                else:
                    p["y"] += 1

        screen.fill(BG_COLOR)
        for y in range(GRID_H):
            for x in range(GRID_W):
                cell = state["board"][y][x]
                if cell is not None:
                    draw_block(screen, x, y, cell)
        if not state["game_over"]:
            p = state["piece"]
            for r, row in enumerate(p["shape"]):
                for c, cell in enumerate(row):
                    if cell:
                        draw_block(screen, p["x"] + c, p["y"] + r, p["color"])
        draw_hud(screen, font, state["score"], state["lines"], state["level"], state["game_over"])
        pygame.display.flip()


if __name__ == "__main__":
    main()
'''
    return _header(ir) + body


# ---------- snake template ----------

def _gen_snake(ir: GameIR) -> str:
    body = f'''
START_LENGTH    = {ir.start_length}
FOOD_COUNT      = {ir.food_count}
WRAP_EDGES      = {ir.wrap_edges}
SPEED_MS        = {ir.snake_speed}
SCORE_PER_FOOD  = {ir.score_per_food}
GAME_OVER_CONDS = {ir.game_over_conditions!r}

SNAKE_COLOR     = ACCENT_COLOR
FOOD_COLOR      = TEXT_COLOR

KEYMAP = {{
{_controls_dict(ir.controls)}
}}

DIRS = {{
    "move_up":    (0, -1),
    "move_down":  (0,  1),
    "move_left":  (-1, 0),
    "move_right": (1,  0),
}}


def spawn_food(snake, foods):
    while True:
        x = random.randrange(GRID_W)
        y = random.randrange(GRID_H)
        if (x, y) not in snake and (x, y) not in foods:
            return (x, y)


def draw_block(surface, x, y, color):
    rect = pygame.Rect(x * BLOCK_SIZE, y * BLOCK_SIZE + HUD_HEIGHT,
                       BLOCK_SIZE, BLOCK_SIZE)
    pygame.draw.rect(surface, color, rect)
    pygame.draw.rect(surface, GRID_COLOR, rect, 1)


def draw_hud(surface, font, score, length, game_over):
    pygame.draw.rect(surface, (0, 0, 0), (0, 0, WINDOW_W, HUD_HEIGHT))
    surface.blit(font.render(f"SCORE {{score}}   LENGTH {{length}}", True, TEXT_COLOR), (10, 8))
    surface.blit(font.render(GAME_NAME, True, ACCENT_COLOR), (10, 32))
    if game_over:
        msg = font.render("GAME OVER — press R to restart, Q to quit", True, ACCENT_COLOR)
        surface.blit(msg, (WINDOW_W // 2 - msg.get_width() // 2,
                           WINDOW_H // 2 - msg.get_height() // 2))


def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption(GAME_NAME + " — RetroLang")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("Courier", 18, bold=True)

    def reset():
        cx, cy = GRID_W // 2, GRID_H // 2
        snake = [(cx - i, cy) for i in range(START_LENGTH)]
        foods = []
        for _ in range(FOOD_COUNT):
            foods.append(spawn_food(snake, foods))
        return {{
            "snake": snake,
            "dir": (1, 0),
            "next_dir": (1, 0),
            "foods": foods,
            "score": 0,
            "tick": 0,
            "paused": False,
            "game_over": False,
        }}

    state = reset()

    while True:
        dt = clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN:
                if event.key == KEYMAP.get("quit"):
                    pygame.quit(); sys.exit(0)
                if event.key == KEYMAP.get("restart"):
                    state = reset(); continue
                if state["game_over"]:
                    if event.key == pygame.K_r:
                        state = reset()
                    elif event.key == pygame.K_q:
                        pygame.quit(); sys.exit(0)
                    continue
                if event.key == KEYMAP.get("pause"):
                    state["paused"] = not state["paused"]
                for action, vec in DIRS.items():
                    if event.key == KEYMAP.get(action):
                        # disallow direct reversal
                        if (vec[0] + state["dir"][0], vec[1] + state["dir"][1]) != (0, 0):
                            state["next_dir"] = vec

        if not state["paused"] and not state["game_over"]:
            state["tick"] += dt
            if state["tick"] >= SPEED_MS:
                state["tick"] = 0
                state["dir"] = state["next_dir"]
                hx, hy = state["snake"][0]
                dx, dy = state["dir"]
                nx, ny = hx + dx, hy + dy
                if WRAP_EDGES:
                    nx %= GRID_W; ny %= GRID_H
                else:
                    if (nx < 0 or nx >= GRID_W or ny < 0 or ny >= GRID_H):
                        if "on_wall_collision" in GAME_OVER_CONDS:
                            state["game_over"] = True
                if not state["game_over"]:
                    if (nx, ny) in state["snake"] and "on_self_collision" in GAME_OVER_CONDS:
                        state["game_over"] = True
                if not state["game_over"]:
                    state["snake"].insert(0, (nx, ny))
                    if (nx, ny) in state["foods"]:
                        state["foods"].remove((nx, ny))
                        state["foods"].append(spawn_food(state["snake"], state["foods"]))
                        state["score"] += SCORE_PER_FOOD
                    else:
                        state["snake"].pop()

        screen.fill(BG_COLOR)
        for (fx, fy) in state["foods"]:
            draw_block(screen, fx, fy, FOOD_COLOR)
        for (sx, sy) in state["snake"]:
            draw_block(screen, sx, sy, SNAKE_COLOR)
        draw_hud(screen, font, state["score"], len(state["snake"]), state["game_over"])
        pygame.display.flip()


if __name__ == "__main__":
    main()
'''
    return _header(ir) + body
